# Generated by Django 3.2 on 2022-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
