# Generated by Django 3.2 on 2022-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_alter_bank_details_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=14)),
                ('Pin', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Debit_Credit', models.CharField(max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
