# Generated by Django 4.2.3 on 2024-02-02 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_alter_transact_details_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transact_details',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
