# Generated by Django 3.2 on 2022-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM_Details',
            fields=[
                ('Account_Number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('Pin_Number', models.IntegerField(null=True, unique=True)),
                ('Mobile', models.BigIntegerField(null=True)),
                ('Amount', models.BigIntegerField(null=True)),
            ],
        ),
    ]
